version: 2

builds:
  - binary: mirage
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
